<?php
namespace App\Controller\Api;

use App\Controller\AppController;

/**
 * Notifications Controller
 *
 */
class NotificationsController extends AppController
{
    /**
     * @throws \Exception
     * @return void
     */
    public function initialize() : void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function getMyNotifications()
    {
        $this->set(['notifications' => []]);
    }

    public function read($id)
    {
        $this->set(['success' => true]);
    }

    public function readAll()
    {
        $this->set(['success' => true]);
    }
}
