<?php
namespace App\Controller\Api;

use App\Controller\AppController;
use App\Controller\Component\notificationComponent;
use App\Model\Entity\CarCount;
use App\Model\Table\CarCountsTable;
use Cake\Datasource\ResultSetInterface;

/**
 * Carcounts Controller
 *
 * @property CarcountsTable $Carcounts
 * @property notificationComponent $notification
 * @method   Carcount[]|ResultSetInterface paginate($object = null, array $settings = [])
 */
class NotificationsController extends AppController
{
    /**
     * @throws \Exception
     * @return void
     */
    public function initialize() : void
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->loadComponent('notification');
    }

    public function getMyNotifications()
    {
        $this->set([
            'notifications' => $this->notification->getNotifications(
            $this->Authentication->getIdentityData('id'),
            1
            )
        ]);
    }

    public function read($id)
    {
        $this->notification->markAsRead($id);
        $this->set(['success' => true]);
    }

    public function readAll()
    {
        $this->notification->markAsRead();
        $this->set(
            [
            'success' => true,
            '_serialize' => 'success',
            ]
        );
    }
}
