<?php
declare(strict_types=1);

namespace App\Controller\Component;

use App\Model\Entity\User;
use ArrayAccess;
use Authentication\Controller\Component\AuthenticationComponent as Authentication;
use Cake\Http\Exception\NotFoundException;
use Cake\Routing\Router;

/**
 * Authentication component
 */
class AuthenticationComponent extends Authentication
{
    /**
     * @param int $user_id The user to login as
     * @return bool
     */
    public function loginAs(int $user_id)
    {
        $user = $this->getController()->getTableLocator()->get('Users')->get($user_id);
        $this->getController()->Authorization->authorize($user, 'canLoginAs');
        $user['_adfAuthentication']['login_as'] = true;
        $this->setIdentity($user);

        return true;
    }

    /**
     * Return the logged in user
     *
     * @return array|ArrayAccess|User
     */
    public function getUser()
    {
        $identity = parent::getIdentity();
        if ($identity) {
            return $identity->getOriginalData();
        } else {
            return null;
        }
    }

    /**
     * @inheritDoc
     */
    public function setIdentity(ArrayAccess $identity)
    {
        parent::setIdentity($identity); // TODO: Change the autogenerated stub
        Router::setRequest($this->getController()->getRequest());

        return $this;
    }
}
