<?php
/**
 * Created by PhpStorm.
 * User: Devinhollister-graham
 * Date: 10/2/18
 * Time: 4:10 PM
 */

namespace App\Controller\Component;

use App\Model\Entity\Myuser;
use Cake\Controller\Component;
use Cake\ORM\TableRegistry;

class TourComponent extends Component
{
    public $component = ['RequestHandler'];

    public function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

    public function checkTour(Myuser $user)
    {
        $this->Tours = TableRegistry::get('Tours');
        $currentController = $this->request->getParam('controller');
        $currentAction = $this->request->getParam('action');

        $completedTours = $this->Tours->find('UsersCompletedTutorials', $user->toArray());

        $searchedValue = $currentController . '-' . $currentAction;

        if (
            array_filter(
                $completedTours,
                function ($e) use ($searchedValue) {
                    return $e->name == $searchedValue;
                }
            )
        ) {
            return false;
        } else {
            return true;
        }
    }
}
